// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOHH4py-O2c36c7LW0sNm7kE-odorAkB8',
    appId: '1:353870955334:web:74785ffea107946f331b47',
    messagingSenderId: '353870955334',
    projectId: 'scamshield-88e7a',
    authDomain: 'scamshield-88e7a.firebaseapp.com',
    storageBucket: 'scamshield-88e7a.firebasestorage.app',
    measurementId: 'G-5241VGP5JK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqe8s0Kz3XFzu9RhynHxiG6dsR24In25I',
    appId: '1:353870955334:android:f5f3c5cc31d4d21c331b47',
    messagingSenderId: '353870955334',
    projectId: 'scamshield-88e7a',
    storageBucket: 'scamshield-88e7a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDH7cl_GAJ1lFG4R6jBfwc7l0jp5xFCgs',
    appId: '1:353870955334:ios:a5d7c7650c34a698331b47',
    messagingSenderId: '353870955334',
    projectId: 'scamshield-88e7a',
    storageBucket: 'scamshield-88e7a.firebasestorage.app',
    iosBundleId: 'com.example.scamShield',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDH7cl_GAJ1lFG4R6jBfwc7l0jp5xFCgs',
    appId: '1:353870955334:ios:a5d7c7650c34a698331b47',
    messagingSenderId: '353870955334',
    projectId: 'scamshield-88e7a',
    storageBucket: 'scamshield-88e7a.firebasestorage.app',
    iosBundleId: 'com.example.scamShield',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOHH4py-O2c36c7LW0sNm7kE-odorAkB8',
    appId: '1:353870955334:web:0b99c689b3ed48e8331b47',
    messagingSenderId: '353870955334',
    projectId: 'scamshield-88e7a',
    authDomain: 'scamshield-88e7a.firebaseapp.com',
    storageBucket: 'scamshield-88e7a.firebasestorage.app',
    measurementId: 'G-XPGTZGCCD8',
  );
}
